lennondj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from music import views

urlpatterns = [
    path('admin/', admin.site.urls),
]

# # The following lines have been put here first, before anything else has been added below,
# # and then they were moved to music/urls.py and music/urls.py was included here (otherwise an exception is raised)
# # urlpatterns += [
# #     path('', views.index, name='index')
# # ]
# urlpatterns += [
#     path('', views.IndexView.as_view(), name='index')
# ]

urlpatterns += [
    path('music/', include('music.urls'))
]

urlpatterns += [
    path('', RedirectView.as_view(url='music/'))
]

music/urls.py
"""URLconfig of the music app.
Different URL patterns for an app are typically specified in the following ways:
    - for function-based views:
        urlpatterns = [
            path('<URL segment>/', views.<the corresponding view function>, name='<the corresponding view name>'>
        ]
    - for class-based views:
        urlpatterns = [
            path('<URL segment>/', views.<the corresponding view class>.as_view(), name='<the corresponding view name>'>
        ]
"""
from django.urls import path

from . import views


# urlpatterns = [
#     path('', views.index, name='index')
# ]
# from .views import BandDeleteView, MusicianDeleteView

urlpatterns = [
    path('', views.IndexView.as_view(), name='index')
]

urlpatterns += [
    path('bands/', views.BandListView.as_view(), name='band-list')
]

urlpatterns += [
    path('bands/<int:pk>/', views.BandDetailView.as_view(), name='band-detail')
]

urlpatterns += [
    path('musicians/', views.MusicianListView.as_view(), name='musician-list')
]

urlpatterns += [
    path('musicians/<int:pk>', views.MusicianDetailView.as_view(), name='musician-detail')
]

urlpatterns += [
    path('bands/create/', views.BandCreateView.as_view(), name='band-create'),
    path('bands/update/<int:pk>', views.BandUpdateView.as_view(), name='band-update'),
    path('bands/delete/<int:pk>', views.BandDeleteView.as_view(), name='band-delete')
]

urlpatterns += [
    path('musicians/create/', views.MusicianCreateView.as_view(), name='musician-create'),
    path('musicians/update/<int:pk>', views.MusicianUpdateView.as_view(), name='musician-update'),
    path('musicians/delete/<int:pk>', views.MusicianDeleteView.as_view(), name='musician-delete')
]

music/models.py
from django.db import models

# Create your models here.
from django.db.models import CharField, IntegerField, ForeignKey, DateField, BooleanField
from django.urls import reverse

from datetime import date

"""
Create some model(s) in the <app>/models.py file
    typical fields:
        models.CharField(max_length=<n>, default='<...>')
        models.BooleanField(verbose_name=<verbose name>, 
		    		        choices=<choices_list>, 
		    		        default=<choice from choices_list>,
		    		        ...)
        models.DateField(null=True, blank=True)
        models.TimeField(null=True, blank=True,
		    		     default=datetime.time(hour=<int>, minute=<int>, second=<int>))
        models.ForeignKey(<AnotherModel>,
		                  on_delete=models.SET_NULL,	# CASCADE, SET_DEFAULT,…
		                  null=True, 
		                  blank=True)
        ...
	typical methods:
	    __str__()
        get_absolute_url()		# return reverse('<model>-detail', args=[str(self.id)])
        ...
Register each model in <app>.admin.py with a separate line like:
    admin.site.register(<Model>)
Run:
    manage.py@<project_site>  > makemigrations <app>
Run:
    manage.py@<project_site>  > migrate
in order to create those model tables in your database
Run another cycle of change models - makemigrations - migrate whenever you make changes to your model(s) / database
Run (optionally):
    manage.py@<project_site>  > sqlmigrate <app> <migration number> 
    (e.g., manage.py@polls_site  > sqlmigrate polls 0001) 
to see the SQL equivalent of a specific migration
"""


class Band(models.Model):
    """The model class describing the concept of a band.
    It includes the band's name, country, and the start and end years.
    """

    name = CharField(max_length=50, default='unknown')
    country = CharField(max_length=50, default='unknown')
    start = IntegerField(null=True, blank=True, default=1962, verbose_name='The year the band started playing together')
    end = IntegerField(null=True, blank=True, default=1970, verbose_name='The year the band stopped playing together')

    def __str__(self):
        return f'{self.name} ({self.start if self.start else "..."}-{self.end if self.end else "..."}), {self.country}'

    def get_absolute_url(self):
        """Returns the URL to access a particular Band instance.
        Enables specific Band pages in admin to include the "View on site" button.
        """

        return reverse('band-detail', args=[str(self.id)])


class Musician(models.Model):
    """The model class describing the concept of a musician.
    It includes the musician's name, reference to the musician's band, their birth date, their primary instrument and
    if they are alive or deceased.
    """

    INSTRUMENT = [
        ('lead guitar', 'lead guitar'),
        ('rhythm guitar', 'rhythm guitar'),
        ('bass', 'bass'),
        ('drums', 'drums'),
        ('vocals', 'vocals')
    ]

    ALIVE = [
        (True, 'alive'),
        (False, 'deceased')
    ]

    name = CharField(max_length=50, default='unknown')
    band = ForeignKey(Band, null=True, blank=True, on_delete=models.SET_NULL)
    born = DateField(null=True, blank=True)
    instrument = CharField(max_length=30, choices=INSTRUMENT, verbose_name='Primary instrument', default='unknown')
    alive = BooleanField(verbose_name='Alive/Deceased', choices=ALIVE, default='alive')
    quote = CharField(max_length=200, default='', null=True, blank=True)

    def __str__(self):
        name_str = f'{self.name}, '
        instrument_str = f'{self.instrument} '
        band_str = f'({self.band if self.band else "solo musician"}), '
        born_str = f'born {self.born.isoformat()}; ' if self.born else 'birth date unknown; '
        # if self.born and isinstance(self.born, date):
        #     born_str = self.born.isoformat()
        # else:
        #     born_str = 'birth date unknown'
        alive_str = f'{"alive" if self.alive else "deceased"}'
        return name_str + instrument_str + band_str + born_str + alive_str

    def get_absolute_url(self):
        """Returns the URL to access a particular Musician instance.
        Enables specific Musician pages in admin to include the "View on site" button.
        """

        return reverse('musician-detail', args=[str(self.id)])

music/views.py
from django.http import HttpResponse
from django.shortcuts import render
# from django.views import View
from django.urls import reverse_lazy
from django.views.generic.base import View

from django.views.generic import TemplateView, DetailView, ListView, CreateView, UpdateView, DeleteView

# Create your views here.


# The very first version of the index view, used only in the setup phase.
# It just prints something in the browser.
# def index(request):
#     return HttpResponse('<h1>John Lennon</h1>')
#     # return HttpResponse(str(request))

# # The next version of the index view, also used only in the setup phase.
# # It renders something in a simple template (index0.html).
# def index(request):
#     context = {
#         'john': 'John Lennon'
#     }
#     return render(request, 'index0.html', context=context)


# class IndexView(TemplateView):
from music.models import Band, Musician

footer_context = {
    'john': 'John Lennon',
    'life_quote': 'Life is what happens to you while you\'re busy making other plans.'
}


class IndexView(View):

    # template_name = 'index0.html'       # unnecessary, probably because of render() in get() specifies it as well
    template_name = 'index.html'       # unnecessary, probably because of render() in get() specifies it as well

    def get(self, request, *args, **kwargs):
        # return HttpResponse('<h1>John Lennon</h1>')
        # context = {
        #     'john': 'John Lennon',
        #     'life_quote': 'Life is what happens to you while you\'re busy making other plans.'
        # }
        context = footer_context
        # return render(request, 'index0.html', context=context)
        return render(request, 'index.html', context=context)


class BandDetailView(DetailView):
    """Class-based view that handles individual Band objects.
    Typical fields that DetailView-based classes specify include:
        - model (class name of the corresponding <Model> class
        - template_name ('<app>/<template file name>'; default: '<app>/<model>_detail.html')
    """

    model = Band
    template_name = 'music/band-detail.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(footer_context)
        return context


class BandListView(ListView):
    """Class-based view that handles lists of Band objects.
    Typical fields that ListView-based classes specify include:
        - model (class name of the corresponding <Model> class
        - template_name ('<app>/<template file name>'; default: '<app>/<model>_list.html')
    Typically, such views also override ListView.get_queryset(),
    making it return a QuerySet of objects (such as (possibly filtered) <Model>.objects.all()))
    """

    model = Band
    template_name = 'music/band-list.html'

    def get_queryset(self):
        return Band.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(footer_context)
        return context


class MusicianDetailView(DetailView):

    """Class-based view that handles individual Musician objects.
    Typical fields that DetailView-based classes specify include:
        - model (class name of the corresponding <Model> class
        - template_name ('<app>/<template file name>'; default: '<app>/<model>_detail.html')
    """

    model = Musician
    template_name = 'music/musician-detail.html'


class MusicianListView(ListView):
    """Class-based view that handles lists of Musician objects.
    Typical fields that ListView-based classes specify include:
        - model (class name of the corresponding <Model> class
        - template_name ('<app>/<template file name>'; default: '<app>/<model>_list.html')
    Typically, such views also override ListView.get_queryset(),
    making it return a QuerySet of objects (such as (possibly filtered) <Model>.objects.all()))
    """

    model = Musician
    template_name = 'music/musician-list.html'

    def get_queryset(self):
        return Musician.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(footer_context)
        return context


class BandCreateView(CreateView):

    model = Band
    fields = '__all__'
    template_name = 'music/band-form.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(footer_context)
        return context


class BandUpdateView(UpdateView):

    model = Band
    fields = '__all__'
    template_name = 'music/band-form.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(footer_context)
        return context


class BandDeleteView(DeleteView):

    model = Band
    success_url = reverse_lazy('band-list')
    template_name = 'music/band-confirm-delete.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(footer_context)
        return context


class MusicianCreateView(CreateView):

    model = Musician
    fields = '__all__'
    template_name = 'music/musician-form.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(footer_context)
        return context


class MusicianUpdateView(UpdateView):

    model = Musician
    fields = '__all__'
    template_name = 'music/musician-form.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(footer_context)
        return context


class MusicianDeleteView(DeleteView):

    model = Musician
    success_url = reverse_lazy('musician-list')
    template_name = 'music/musician-confirm-delete.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(footer_context)
        return context

templates/music/band-confirm-delete.html
{%  extends 'base.html' %}

{% block name %}
    {{ john }}
{% endblock %}
{% block quote %}
    {{ life_quote }}
{% endblock %}

{% block content %}
    <p>Delete musician: {{ band.name }}?</p>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete">
        &nbsp; &nbsp;
        <a href="{% url 'band-detail' band.pk %}">No, keep it</a>
    </form>
{% endblock %}


{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{##}
{#</body>#}
{#</html>#}

templates/music/band-detail.html
{% extends 'base.html' %}

{% block quote %}
    {{ life_quote }}
{% endblock %}
{% block name %}
    {{ john }}
{% endblock %}

{% block content %}
{#    <div>#}
        <p>{{ band }}</p>

        {% if band.musician_set.all %}
            {% for musician in band.musician_set.all %}
                <li><a href="{% url 'musician-detail' musician.pk %}">{{ musician.name }}</a></li>
            {% endfor %}
        {% else %}
            <p>Band members unknown.</p>
        {% endif %}

        <br>
        <p>
            <a href="{% url 'band-update' band.pk %}">Update band</a> <br>
            <a href="{% url 'band-delete' band.pk %}">Delete band</a>
        </p>
{#    </div>#}
{% endblock %}

{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{##}
{#</body>#}
{#</html>#}

templates/music/band-form.html
{% extends 'base.html' %}

{% block name %}
    {{ john }}
{% endblock %}
{% block quote %}
    {{ life_quote }}
{% endblock %}

{% block content %}
    <p>Create/Update band</p>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}


{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{##}
{#</body>#}
{#</html>#}

templates/music/band-list.html
{% extends 'base.html' %}

{% block name %}
    {{ john }}
{% endblock %}
{% block quote %}
    {{ life_quote }}
{% endblock %}

{% block content %}
    {% if band_list %}
        <p>The bands registered in the database so far ({{ band_list.count }}):</p>
        {% for band in band_list %}
{#            <li>{{ band }}</li>#}
            <li><a href="{% url 'band-detail' band.pk %}">{{ band.name }}</a></li>
        {% endfor %}
    {% else %}
        <p>No band is registered in the database.</p>
    {% endif %}

    <br>
    <p>
        <a href="{% url 'band-create' %}">Add band</a>
    </p>
{% endblock %}

templates/music/musician-confirm-delete.html
{%  extends 'base.html' %}

{% block quote %}
    {% if musician.quote %}
        {{ musician.quote }}
    {% else %}
        {{ life_quote }}
    {% endif %}
{% endblock %}
{% block name %}
    {% if musician.quote %}
        {{ musician.name }}
    {% else %}
        {{ john }}
    {% endif %}
{% endblock %}

{% block content %}
    <p>Delete musician: {{ musician.name }}?</p>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete">
        &nbsp; &nbsp;
        <a href="{% url 'musician-detail' musician.pk %}">No, keep it</a>
    </form>
{% endblock %}



{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{##}
{#</body>#}
{#</html>#}

templates/music/musician-detail.html
{% extends 'base.html' %}

{% block quote %}
    {% if musician.quote %}
        {{ musician.quote }}
    {% else %}
        {{ life_quote }}
    {% endif %}
{% endblock %}
{% block name %}
    {% if musician.quote %}
        {{ musician.name }}
    {% else %}
        {{ john }}
    {% endif %}
{% endblock %}

{% block content %}
    <p>
        {{ musician }}
    </p>

    <p>
        <a href="{% url 'musician-update' musician.pk %}">Update musician</a> <br>
        <a href="{% url 'musician-delete' musician.pk %}">Delete musician</a>
    </p>
{% endblock %}


{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{##}
{#</body>#}
{#</html>#}

templates/music/musician-form.html
{% extends 'base.html' %}

{% block quote %}
    {% if musician.quote %}
        {{ musician.quote }}
    {% else %}
        {{ life_quote }}
    {% endif %}
{% endblock %}
{% block name %}
    {% if musician.quote %}
        {{ musician.name }}
    {% else %}
        {{ john }}
    {% endif %}
{% endblock %}

{% block content %}
    <p>Create/Update musician</p>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}


{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{##}
{#</body>#}
{#</html>#}

templates/music/musician-list.html
{% extends 'base.html' %}

{% block quote %}
    {{ life_quote }}
{% endblock %}
{% block name %}
    {{ john }}
{% endblock %}

{% block content %}
    {% if musician_list %}
        <p>The musicians registered in the database so far ({{ musician_list.count }}):</p>
        {% for musician in musician_list %}
{#            <li>{{ musician }}</li>#}
            <li><a href="{% url 'musician-detail' musician.pk %}">{{ musician.name }}</a></li>
{#            <li><a href="{% url 'musician-detail' musician.pk %}"></a>{{ musician.name }}</li>#}
        {% endfor %}
    {% else %}
        <p>No musician is registered in the database.</p>
    {% endif %}

    <br>
    <p>
        <a href="{% url 'musician-create' %}">Add musician</a>
    </p>
{% endblock %}


{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{##}
{#</body>#}
{#</html>#}